name: RoboTwin
channels:
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=6_kmp_llvm
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.40=ha1999f0_7
  - binutils_linux-64=2.40=hb3c18ed_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-gcc-specs=11.4.0=h4caf5ac_13
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cccl_linux-64=12.9.27=ha770c72_0
  - cuda-crt-dev_linux-64=12.9.86=ha770c72_2
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart-dev=12.9.79=h5888daf_0
  - cuda-cudart-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart-static=12.9.79=h5888daf_0
  - cuda-cudart-static_linux-64=12.9.79=h3f2d84a_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-driver-dev_linux-64=12.9.79=h3f2d84a_0
  - cuda-libraries=12.9.1=ha770c72_0
  - cuda-nvcc=12.9.86=hcdd1206_4
  - cuda-nvcc-dev_linux-64=12.9.86=he91c749_2
  - cuda-nvcc-impl=12.9.86=h85509e4_2
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvcc_linux-64=12.9.86=he0b4e1d_4
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-dev_linux-64=12.9.86=ha770c72_2
  - cuda-nvvm-impl=12.9.86=h4bc722e_2
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-opencl=12.9.19=h5888daf_0
  - cuda-runtime=12.9.1=0
  - cuda-version=12.9=h4f385c5_3
  - cudatoolkit-dev=11.7.0=h72bdee0_6
  - cudnn=9.10.2.21=hbcb9cd8_0
  - dataclasses=0.8=pyhc8e2a94_3
  - filelock=3.20.0=pyhd8ed1ab_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gcc=11.4.0=h602e360_13
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - icu=75.1=he02047a_0
  - iopath=0.1.10=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - kernel-headers_linux-64=6.12.0=he073ed8_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=2_h0358290_openblas
  - libcublas=12.9.1.4=h676940d_1
  - libcublas-dev=12.9.1.4=h676940d_1
  - libcudnn=9.10.2.21=hf7e9902_0
  - libcudnn-dev=9.10.2.21=h58dd1b1_0
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcusolver=11.7.5.82=h676940d_2
  - libcusolver-dev=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libcusparse-dev=12.5.10.65=hecca717_2
  - libdeflate=1.25=h17f619e_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=2_h47877c9_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.8.0=h0af6554_0
  - libmagma_sparse=2.8.0=h0af6554_0
  - libmlir14=14.0.6=he0ac6c6_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.4.1.87=h676940d_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.9.82=hecca717_1
  - libnvjitlink=12.9.86=hecca717_2
  - libnvjpeg=12.4.0.76=hecca717_1
  - libnvptxcompiler-dev=12.9.86=ha770c72_2
  - libnvptxcompiler-dev_linux-64=12.9.86=ha770c72_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.3=h6128344_1
  - libsanitizer=11.4.0=h5763a12_13
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.4.1=cuda120_mkl_h8315a94_306
  - libudev1=258.2=h6569c3e_1
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lit=21.1.6=pyhd8ed1ab_0
  - llvm-openmp=21.1.6=h4922eb0_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2024.2.2=ha770c72_17
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py310h03d9f68_0
  - pillow=12.0.0=py310h80abafc_0
  - pip=25.3=pyh8b19718_0
  - portalocker=3.2.0=py310hff52083_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=2.13.6=pyhff21bea_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.4.1=cuda120_mkl_py310_h1a43862_306
  - pyyaml=6.0.3=py310h3406613_0
  - rdma-core=60.0=hecca717_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sleef=3.9.0=ha0421bc_0
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.39=hc4b9eeb_2
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.13.0=h8d10470_4
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - triton=2.0.0=cuda120py310h2ad3591_4
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h280c20c_3
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - ConfigArgParse==1.7.1
    - Farama-Notifications==0.0.4
    - Flask==3.1.2
    - GitPython==3.1.45
    - PyJWT==2.10.1
    - Pygments==2.19.2
    - Werkzeug==3.1.3
    - adal==1.2.7
    - addict==2.4.0
    - annotated-types==0.7.0
    - anyio==4.11.0
    - asciitree==0.3.3
    - asttokens==3.0.1
    - attrs==25.4.0
    - av==16.0.1
    - azure==4.0.0
    - azure-ai-inference==1.0.0b9
    - azure-applicationinsights==0.1.1
    - azure-batch==4.1.3
    - azure-common==1.1.28
    - azure-core==1.36.0
    - azure-cosmosdb-nspkg==2.0.2
    - azure-cosmosdb-table==1.0.6
    - azure-datalake-store==0.0.53
    - azure-eventgrid==1.3.0
    - azure-graphrbac==0.40.0
    - azure-keyvault==1.1.0
    - azure-loganalytics==0.1.1
    - azure-mgmt==4.0.0
    - azure-mgmt-advisor==1.0.1
    - azure-mgmt-applicationinsights==0.1.1
    - azure-mgmt-authorization==0.50.0
    - azure-mgmt-batch==5.0.1
    - azure-mgmt-batchai==2.0.0
    - azure-mgmt-billing==0.2.0
    - azure-mgmt-cdn==3.1.0
    - azure-mgmt-cognitiveservices==3.0.0
    - azure-mgmt-commerce==1.0.1
    - azure-mgmt-compute==4.6.2
    - azure-mgmt-consumption==2.0.0
    - azure-mgmt-containerinstance==1.5.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-containerservice==4.4.0
    - azure-mgmt-cosmosdb==0.4.1
    - azure-mgmt-datafactory==0.6.0
    - azure-mgmt-datalake-analytics==0.6.0
    - azure-mgmt-datalake-nspkg==3.0.1
    - azure-mgmt-datalake-store==0.5.0
    - azure-mgmt-datamigration==1.0.0
    - azure-mgmt-devspaces==0.1.0
    - azure-mgmt-devtestlabs==2.2.0
    - azure-mgmt-dns==2.1.0
    - azure-mgmt-eventgrid==1.0.0
    - azure-mgmt-eventhub==2.6.0
    - azure-mgmt-hanaonazure==0.1.1
    - azure-mgmt-iotcentral==0.1.0
    - azure-mgmt-iothub==0.5.0
    - azure-mgmt-iothubprovisioningservices==0.2.0
    - azure-mgmt-keyvault==1.1.0
    - azure-mgmt-loganalytics==0.2.0
    - azure-mgmt-logic==3.0.0
    - azure-mgmt-machinelearningcompute==0.4.1
    - azure-mgmt-managementgroups==0.1.0
    - azure-mgmt-managementpartner==0.1.1
    - azure-mgmt-maps==0.1.0
    - azure-mgmt-marketplaceordering==0.1.0
    - azure-mgmt-media==1.0.1
    - azure-mgmt-monitor==0.5.2
    - azure-mgmt-msi==0.2.0
    - azure-mgmt-network==2.7.0
    - azure-mgmt-notificationhubs==2.1.0
    - azure-mgmt-nspkg==3.0.2
    - azure-mgmt-policyinsights==0.1.0
    - azure-mgmt-powerbiembedded==2.0.0
    - azure-mgmt-rdbms==1.9.0
    - azure-mgmt-recoveryservices==0.3.0
    - azure-mgmt-recoveryservicesbackup==0.3.0
    - azure-mgmt-redis==5.0.0
    - azure-mgmt-relay==0.1.0
    - azure-mgmt-reservations==0.2.1
    - azure-mgmt-resource==2.2.0
    - azure-mgmt-scheduler==2.0.0
    - azure-mgmt-search==2.1.0
    - azure-mgmt-servicebus==0.5.3
    - azure-mgmt-servicefabric==0.2.0
    - azure-mgmt-signalr==0.1.1
    - azure-mgmt-sql==0.9.1
    - azure-mgmt-storage==2.0.0
    - azure-mgmt-subscription==0.2.0
    - azure-mgmt-trafficmanager==0.50.0
    - azure-mgmt-web==0.35.0
    - azure-nspkg==3.0.2
    - azure-servicebus==0.21.1
    - azure-servicefabric==6.3.0.0
    - azure-servicemanagement-legacy==0.20.8
    - azure-storage-blob==1.5.0
    - azure-storage-common==1.4.2
    - azure-storage-file==1.4.0
    - azure-storage-queue==1.4.0
    - blinker==1.9.0
    - certifi==2025.11.12
    - cffi==2.0.0
    - chardet==5.2.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - colorlog==6.10.1
    - comm==0.2.3
    - contourpy==1.3.2
    - cryptography==46.0.3
    - cycler==0.12.1
    - dash==3.3.0
    - decorator==5.2.1
    - distro==1.9.0
    - embreex==2.17.7.post7
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fasteners==0.20
    - fastjsonschema==2.21.2
    - ffmpeg==1.4
    - fonttools==4.60.1
    - gitdb==4.0.12
    - gymnasium==0.29.1
    - h11==0.16.0
    - h5py==3.15.1
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.25.0
    - idna==3.11
    - imageio==2.34.2
    - imageio-ffmpeg==0.6.0
    - importlib_metadata==8.7.0
    - importlib_resources==6.5.2
    - ipython==8.37.0
    - ipywidgets==8.1.8
    - isodate==0.7.2
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jiter==0.12.0
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter_core==5.9.1
    - jupyterlab_widgets==3.0.16
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - lxml==6.0.2
    - manifold3d==3.3.2
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - moviepy==2.2.1
    - mplib==0.2.1
    - msal==1.34.0
    - msrest==0.7.1
    - msrestazure==0.6.4.post1
    - narwhals==2.12.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - numcodecs==0.13.1
    - numpy==1.26.4
    - numpy-quaternion==2024.0.13
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - nvidia_curobo==0.0.0
    - oauthlib==3.3.1
    - open3d==0.18.0
    - openai==2.8.1
    - opencv-python==4.11.0.86
    - packaging==25.0
    - pandas==2.3.3
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.5.0
    - plotly==6.5.0
    - proglog==0.1.12
    - prompt_toolkit==3.0.52
    - protobuf==6.33.1
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - pycollada==0.9.2
    - pycparser==2.23
    - pydantic==2.12.4
    - pydantic_core==2.41.5
    - pyglet==1.5.31
    - pyparsing==3.2.5
    - pyperclip==1.11.0
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytorch3d==0.7.8
    - pytz==2025.2
    - referencing==0.37.0
    - requests==2.32.5
    - requests-oauthlib==2.0.0
    - retrying==1.4.2
    - rpds-py==0.29.0
    - rtree==1.4.1
    - sapien==3.0.0b1
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - sentry-sdk==2.45.0
    - setuptools-scm==9.2.2
    - shapely==2.1.2
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - stack-data==0.6.3
    - svg.path==7.0
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - tomli==2.3.0
    - toppra==0.6.3
    - torchvision==0.19.1
    - traitlets==5.14.3
    - transforms3d==0.4.2
    - trimesh==4.4.3
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - vhacdx==0.0.9
    - wandb==0.23.0
    - warp-lang==1.10.0
    - wcwidth==0.2.14
    - widgetsnbextension==4.0.15
    - xatlas==0.0.11
    - xxhash==3.6.0
    - yourdfpy==0.0.58
    - zarr==2.18.3
    - zipp==3.23.0

prefix: "/home/pologue/.local/share/mamba/envs/RoboTwin"
